[theme]
# Primary color
primary = "#2E86C1"

# Secondary color
secondary = "#85C1E9"

# Neutral color
neutral = "#F5F5F5"

# Accent color
accent = "#3498DB"

# Background color
background = "#FFFFFF"

# Font settings
font_family = "Inter"

[ui]
# Chat bubble settings
bubble_border_radius = "12px"

# Message settings
message_border_radius = "12px"
message_padding = "12px"

# Code block settings
code_block_border_radius = "8px"
code_block_padding = "8px"

[features]
# Enable/disable features
multi_modal = true
latex = true
speech_to_text = false
code_highlighting = true

[project]
# Project settings
name = "NIH Research Grant Assistant"
description = "AI-powered assistant for NIH funding opportunities and budget planning"

[markdown]
# Markdown rendering settings
default = true
math = true
highlight = true 